LIB_NAME=RatelPlayer
#If code is modified, increase the version and set _UPDATED to true. Only that version will be updated.
#For development versions, set SNAPSHOT to true to allow continuous updates
#maven ? ??? ??? ???? Shapshot ? ???? ?? ??? 3??? ???
GROUP=ai.shortform-play.sdk.ratel.player.android
YOUTUBE_PLAYER=12.1.1.1.7
YOUTUBE_PLAYER_UPDATED=true

CORE_VERSION=0.0.5
CORE_UPDATED=true

UI_VERSION=0.0.2
UI_UPDATED=true

UTIL_VERSION=0.0.0.4
UTIL_UPDATED=true

SNAPSHOT=false