LIB_NAME=RatelPlayer
#If code is modified, increase the version and set _UPDATED to true. Only that version will be updated.
#For development versions, set SNAPSHOT to true to allow continuous updates

GROUP=ai.shortform-play.sdk.ratel.player.android
YOUTUBE_PLAYER=12.1.1.1.3
YOUTUBE_PLAYER_UPDATED=false
CORE_VERSION=0.0.0.3.5
CORE_UPDATED=true
UI_VERSION=0.0.0.1.2
UI_UPDATED=false
AD_VERSION=0.0.0.1.2
AD_UPDATED=false
UTIL_VERSION=0.0.0.3.1
UTIL_UPDATED=false
SNAPSHOT=true